manifest = "f00d9be01566faa9bf582331579ca86c8996def384bc58fca6ab166baff91690"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
target = "//:core"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.68.0" ]
revision = "7bb721fada1196b951719650a1df2e36f97052ac"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.68.0" ]
revision = "c7d32953c472ce021b1badc7bdbaa1aa3aa44099"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.68.0" ]
revision = "e70f2c918cfb1842839dfffe8464623698f14be0"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.68.0" ]
revision = "bfac67328a5bf3ec019e0e6c86f67ec7a86a8aeb"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.68.0" ]
revision = "fd99813dd6f149cd14f12c31bcbcc749162a7d53"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.68.0" ]
revision = "a1efd5fee01e149f8e28a4f762932d472da9b10a"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.68.0" ]
revision = "eec9292e54f780ab8cf90211faffc796d9c8c9ed"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.68.0" ]
revision = "ab18fef159fa05e369a5ac56fb29fa5d1ada0155"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.68.0" ]
revision = "aa8cb7b3f809abcb8ca323fbfe806a073f5fa40a"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.68.0" ]
revision = "00a45970c7a31ccfba0fe52c6188be944db21871"
