targets = ["//:ratio"]

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.65.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
version = "1.65.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
version = "1.65.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
version = "1.65.1"