targets = ["//:ratio"]

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.54.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
version = "1.54.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
version = "1.54.0"