targets = [ "//:ratio" ]

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
version = "branch=master"
